=== Belafon/data_formats/NPRG036-HW3-T3G5/xml/schemas/schema-1.xsd
<?xml version="1.0" encoding="UTF-8"?>

<xs:schema 
    xmlns:xs="http://www.w3.org/2001/XMLSchema"
    xmlns="http://mojezoo.cz/"
    targetNamespace="http://mojezoo.cz/">
    
    <xs:import namespace="http://www.w3.org/XML/1998/namespace"
    schemaLocation="https://www.w3.org/2009/01/xml.xsd" />

    <xs:element name="Zoo">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="Pavilon" maxOccurs="unbounded" minOccurs="0"/>
                <xs:element ref="TypyZvířat" maxOccurs="1" minOccurs="0"/>
                <xs:element ref="TypyStrav" maxOccurs="1" minOccurs="0"/>
                <xs:element ref="Zaměstnanci" maxOccurs="1" minOccurs="0"/>
                <xs:element ref="Výběhy" maxOccurs="1" minOccurs="0"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    



    <xs:element name="název" type="xs:ID"/> 
    <xs:element name="datumPosledníRekonstrukce" type="xs:date"/>
    <xs:element name="datumVýstavby" type="xs:date"/>
    
    <xs:element name="Pavilon">
        <xs:complexType>
            <xs:sequence minOccurs="0" maxOccurs="1">
                <xs:element ref="název" maxOccurs="1" />
                <xs:element ref="datumVýstavby" maxOccurs="1"/>
                <xs:element ref="datumPosledníRekonstrukce" maxOccurs="1"/>
                <xs:element ref="Výběh" maxOccurs="unbounded"/>
                <xs:element ref="PrůvodcePavilonem" maxOccurs="unbounded"/>
            </xs:sequence>
            <xs:attribute name="ref" type="xs:IDREF"></xs:attribute>
        </xs:complexType>
    </xs:element>

    
    <xs:element name="lokaceNaMapě" type="xs:string"/>
    <xs:element name="průměrnáTeplota" type="xs:integer"/>
    <xs:element name="popis">
        <xs:complexType>
            <xs:simpleContent>
                <xs:extension base="xs:string">
                    <xs:attribute ref="xml:lang" use="required" />
                </xs:extension>
            </xs:simpleContent>
        </xs:complexType>
    </xs:element>
    
    <xs:element name="Výběh">
        <xs:complexType>
            <xs:sequence minOccurs="0" maxOccurs="1">
                <xs:element ref="název"/>
                <xs:element ref="názevProČtení"/>
                <xs:element ref="lokaceNaMapě"/>
                <xs:element ref="datumVýstavby"/>
                <xs:element ref="průměrnáTeplota" maxOccurs="1" minOccurs="0"/>
                <xs:element ref="popis"/>
                <xs:element ref="ZvířeTyp" maxOccurs="unbounded" minOccurs="0"/>
                <xs:element ref="Zvíře" maxOccurs="unbounded" minOccurs="0"/>
                <xs:element ref="Veterinář" maxOccurs="unbounded" minOccurs="1"/>
                <xs:element ref="Pečovatel" maxOccurs="unbounded" minOccurs="1"/>
            </xs:sequence>
            <xs:attribute name="ref" type="xs:IDREF"></xs:attribute>
        </xs:complexType>
    </xs:element>

    
    <xs:element name="jméno" type="xs:string" />
    <xs:element name="popisZdravotníhoStavu" >
        <xs:complexType>
            <xs:simpleContent>
                <xs:extension base="xs:string">
                    <xs:attribute ref="xml:lang" use="required" />
                </xs:extension>
            </xs:simpleContent>
        </xs:complexType>
    </xs:element>
    <xs:element name="datumNarození" type="xs:date"/>
    <xs:element name="datumPříchoduDoZoo" type="xs:date"/>
    <xs:element name="Zvíře">
        <xs:complexType>
            <xs:sequence maxOccurs="1">
                <xs:element ref="jméno" maxOccurs="1"/>
                <xs:element ref="popisZdravotníhoStavu" maxOccurs="1"/>
                <xs:element ref="datumNarození" maxOccurs="1"/>
                <xs:element ref="datumPříchoduDoZoo" maxOccurs="1"/>
                <xs:element ref="ZvířeTyp" />
            </xs:sequence>
        </xs:complexType>
    </xs:element>








    
    <xs:element name="TypyZvířat">
        <xs:complexType>
            <xs:sequence minOccurs="0" maxOccurs="unbounded">
                <xs:element ref="ZvířeTyp"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="ZvířeTyp">
        <xs:complexType>
            <xs:sequence minOccurs="0" maxOccurs="1">
                <xs:element ref="název" maxOccurs="1"/>
                <xs:element ref="názevProČtení" maxOccurs="unbounded"/>
                <xs:element ref="popis" maxOccurs="1"/>
                <xs:element ref="popisChovu" maxOccurs="1"/>
                <xs:element ref="TypStravy" maxOccurs="unbounded"/>
                <xs:element ref="Výběh" maxOccurs="unbounded" minOccurs="0"/>
            </xs:sequence>
            <xs:attribute name="ref" type="xs:IDREF"></xs:attribute>
        </xs:complexType>
    </xs:element>

  
    <xs:element name="názevProČtení">
        <xs:complexType>
            <xs:simpleContent>
                <xs:extension base="xs:string">
                    <xs:attribute ref="xml:lang" use="required" />
                </xs:extension>
            </xs:simpleContent>
        </xs:complexType>
    </xs:element>

    <xs:element name="popisChovu">
        <xs:complexType>
            <xs:simpleContent>
                <xs:extension base="xs:string">
                    <xs:attribute ref="xml:lang" use="required" />
                </xs:extension>
            </xs:simpleContent>
        </xs:complexType>
    </xs:element>
  
    <xs:element name="výskytVZoo">
        <xs:complexType>
            <xs:simpleContent>
                <xs:extension base="xs:string">
                    <xs:attribute ref="xml:lang" use="required" />
                </xs:extension>
            </xs:simpleContent>
        </xs:complexType>
    </xs:element>


    <xs:element name="Výběhy">
        <xs:complexType>
            <xs:sequence minOccurs="0" maxOccurs="unbounded">
                <xs:element ref="Výběh"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>












    <xs:element name="TypyStrav">
        <xs:complexType>
            <xs:sequence minOccurs="0" maxOccurs="unbounded">
                <xs:element ref="TypStravy" />
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="TypStravy">
        <xs:complexType>
            <xs:sequence minOccurs="0">
                <xs:element ref="cena" maxOccurs="1"/>
                <xs:element ref="kalorie" maxOccurs="1"/>
            </xs:sequence>
            <xs:attribute name="název" type="xs:ID"></xs:attribute>
            <xs:attribute name="ref" type="xs:IDREF"></xs:attribute>
        </xs:complexType>
    </xs:element>

    <xs:simpleType name="moneyValue">
        <xs:restriction base="xs:integer">
            <xs:minInclusive value="0" />
        </xs:restriction>
    </xs:simpleType>
        
    <xs:element name="cena" type="prizeValue"> 

    </xs:element>

    <xs:element name="kalorie" >
        <xs:simpleType>
            <xs:restriction base="xs:integer">
                <xs:minInclusive value="0"/>
            </xs:restriction>
        </xs:simpleType>
    </xs:element>

    <xs:complexType name="prizeValue">
        <xs:simpleContent>
            <xs:extension base="moneyValue">
                <xs:attribute  name="currency" use="required">
                    <xs:simpleType>
                        <xs:restriction base="xs:string">
                            <xs:enumeration value="CZK"/>
                            <xs:enumeration value="EUR"/>
                            <xs:enumeration value="USD"/>
                        </xs:restriction>
                    </xs:simpleType>
                </xs:attribute>
                <xs:attribute name="název" type="xs:ID" use="required"></xs:attribute>
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>











    <xs:element name="givenName" type="xs:string" />
    <xs:element name="familyName" type="xs:string" />
    <xs:element name="plat" type="prizeValue"/>
    <xs:element name="telefonníČíslo">
        <xs:simpleType>
            <xs:restriction base="xs:string">
                <xs:pattern value="tel:\+[0-9]{3}([ ]?[0-9]{3}){3}"></xs:pattern>
            </xs:restriction>
        </xs:simpleType> 
    </xs:element>

    <xs:complexType name="Zaměstnanec" >
        <xs:sequence minOccurs="0">
            <xs:element ref="givenName" />
            <xs:element ref="familyName" />
            <xs:element ref="plat"/>
            <xs:element ref="telefonníČíslo" minOccurs="0"/>
        </xs:sequence>
        <xs:attribute name="název" type="xs:ID"></xs:attribute>
        <xs:attribute name="ref" type="xs:IDREF"></xs:attribute>
    </xs:complexType>



    <xs:element name="PrůvodcePavilonem"> 
        <xs:complexType>
            <xs:complexContent>
                <xs:extension base="Zaměstnanec" >
                    <xs:sequence minOccurs="0">
                        <xs:element ref="provádí" maxOccurs="1" minOccurs="1"/>
                    </xs:sequence>
                </xs:extension>
            </xs:complexContent>
        </xs:complexType>
    </xs:element>
    
    <xs:element name="provádí">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="Pavilon" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="pečuje">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="Výběh" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="spravuje">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="Výběh" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="Veterinář" >
        <xs:complexType>
            <xs:complexContent>
                <xs:extension base="Zaměstnanec" >
                    <xs:sequence minOccurs="0">
                        <xs:element ref="pečuje" maxOccurs="1" minOccurs="1" />
                    </xs:sequence>
                </xs:extension>
            </xs:complexContent>
        </xs:complexType>
    </xs:element>

    <xs:element name="Pečovatel">
        <xs:complexType>
            <xs:complexContent>
                <xs:extension base="Zaměstnanec">
                    <xs:sequence minOccurs="0">
                        <xs:element ref="spravuje" maxOccurs="1" minOccurs="1" />
                    </xs:sequence>
                </xs:extension>
            </xs:complexContent>
        </xs:complexType>
    </xs:element>

    <xs:element name="Uklízeč">
        <xs:complexType>
            <xs:complexContent>
                <xs:extension base="Zaměstnanec" />
            </xs:complexContent>
        </xs:complexType>
    </xs:element>

    <xs:element name="Zaměstnanci">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="Uklízeč" minOccurs="0" maxOccurs="unbounded"/>
                <xs:element ref="Pečovatel" minOccurs="0" maxOccurs="unbounded"/>
                <xs:element ref="Veterinář" minOccurs="0" maxOccurs="unbounded"/>
                <xs:element ref="PrůvodcePavilonem"  minOccurs="0" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>



</xs:schema>

=== Belafon/data_formats/NPRG036-HW3-T3G5/data/data-1.xml
<?xml version="1.0" encoding="utf-8"?>
<Zoo 
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:xsd="http://www.w3.org/2001/XMLSchema"
    xsi:schemaLocation="http://mojezoo.cz/ ./../schemas/schema-1.xsd"
    xmlns="http://mojezoo.cz/">
    <Pavilon>
        <název>Afrika</název>
        <datumVýstavby>2004-06-01</datumVýstavby>
        <datumPosledníRekonstrukce>2020-02-05</datumPosledníRekonstrukce>
        <Výběh>
            <název>Savana</název>
            <lokaceNaMapě>S1</lokaceNaMapě>
            <datumVýstavby>2002-09-24</datumVýstavby>
            <popis xml:lang="cs">1200 m^2 rovinné travnaté plochy,  na okrajích s velkými rozestupy rostou baobaby a blahovičníky.</popis>
            
            <ZvířeTyp></ZvířeTyp>

            <Zvíře>
                <jméno>Černobíl</jméno>
	            <popisZdravotníhoStavu xml:lang="cs">Zdravý jedinec</popisZdravotníhoStavu>  
	            <datumNarození>2012-04-02</datumNarození>
            	<datumPříchoduDoZoo>2012-04-02</datumPříchoduDoZoo>
                <ZvířeTyp názevTypu="Zebra" />
            </Zvíře>

            <Zvíře>
                <jméno>Erin</jméno>
	            <popisZdravotníhoStavu xml:lang="cs">Zdravý jedinec</popisZdravotníhoStavu>  
	            <datumNarození>2010-01-10</datumNarození>
            	<datumPříchoduDoZoo>2010-01-10</datumPříchoduDoZoo>
                <ZvířeTyp názevTypu="Zebra" />
            </Zvíře>

            <Zvíře>
                <jméno>Bessie</jméno> 
	            <popisZdravotníhoStavu xml:lang="cs">Zdravý jedinec</popisZdravotníhoStavu>  
	            <datumNarození>2009-05-12</datumNarození>
            	<datumPříchoduDoZoo>2010-01-18</datumPříchoduDoZoo>
                <ZvířeTyp názevTypu="Zebra" />
            </Zvíře>

            <Veterinář názevTypu="Veterinář_1"/>
            <Pečovatel názevTypu="Pečovatel_1"/>
        </Výběh>
        
        <Výběh>
            <název>Poušť</název>
            <lokaceNaMapě>S2</lokaceNaMapě>
            <datumVýstavby>2003-08-19</datumVýstavby>
            <popis xml:lang="cs">1500 m^2 rovinné písčité plochy,  na levém okraji roste mix listnatých stromů. </popis>
            <Veterinář názevTypu="Veterinář_1"/>
            <Pečovatel názevTypu="Pečovatel_1"/>
        </Výběh>

        <Výběh>
            <název>Hory</název>
            <lokaceNaMapě>S3</lokaceNaMapě>
            <datumVýstavby>2005-06-02</datumVýstavby>
            <popis xml:lang="cs">1000 m^2 plochy strmitých skalisek. </popis>
            <Veterinář názevTypu="Veterinář_1"/>
            <Pečovatel názevTypu="Pečovatel_1"/>
        </Výběh>

        <Výběh>
            <název>TeráriumKober</název>
            <lokaceNaMapě>S3</lokaceNaMapě>
            <datumVýstavby>2005-06-02</datumVýstavby>
            <popis xml:lang="cs">1000 m^2 plochy strmitých skalisek. </popis>
            <Veterinář názevTypu="Veterinář_1"/>
            <Pečovatel názevTypu="Pečovatel_1"/>
        </Výběh>

        <Výběh>
            <název>VýběhGoril</název>
            <lokaceNaMapě>S3</lokaceNaMapě>
            <datumVýstavby>2005-06-02</datumVýstavby>
            <popis xml:lang="cs">1000 m^2 plochy strmitých skalisek. </popis>
            <Veterinář názevTypu="Veterinář_1"/>
            <Pečovatel názevTypu="Pečovatel_1"/>
        </Výběh>

        <PrůvodcePavilonem názevTypu="Průvodce_pavilonem_1"/>
    </Pavilon>



    <Pavilon>
        <název>Plazy</název>
        <datumVýstavby>2004-06-01</datumVýstavby>
        <datumPosledníRekonstrukce>2020-02-05</datumPosledníRekonstrukce>

        <Výběh>
            <název>TeráriumKober</název>
            <lokaceNaMapě>PL1</lokaceNaMapě>
            <datumVýstavby>2011-04-01</datumVýstavby>
            <popis xml:lang="cs">4 m^2 plochy, prosklenné terrárium s umělým jezírkem a starými dubovými větvemi </popis>
            <Zvíře>
                <jméno>Lenka</jméno>  
	            <popisZdravotníhoStavu xml:lang="cs">Zdravý jedinec</popisZdravotníhoStavu>  
	            <datumNarození>2015-03-01</datumNarození>
            	<datumPříchoduDoZoo>2018-05-10</datumPříchoduDoZoo>
                <ZvířeTyp názevTypu="KobraKrálovská" />
            </Zvíře>            
            <Veterinář názevTypu="Veterinář_1"/>
            <Pečovatel názevTypu="Pečovatel_1"/>
        </Výběh>
        
        <PrůvodcePavilonem názevTypu="Průvodce_pavilonem_1"/>
    </Pavilon>

    <Pavilon>
        <název>Prales</název>
        <datumVýstavby>2004-06-01</datumVýstavby>
        <datumPosledníRekonstrukce>2018-04-08</datumPosledníRekonstrukce>

        <Výběh>
            <název>VýběhGoril</název>
            <lokaceNaMapě>PR2</lokaceNaMapě>
            <datumVýstavby>2010-04-12</datumVýstavby>
            <popis xml:lang="cs">100 m^2 plochy, prosklenný plot, nerovný travnatý povrch, roste zde několik dubů.</popis>
            <Zvíře>
                <jméno>George</jméno>
	            <popisZdravotníhoStavu xml:lang="cs">Zdravý jedinec</popisZdravotníhoStavu>
	            <datumNarození>1995-05-12</datumNarození>
            	<datumPříchoduDoZoo>2005-01-18</datumPříchoduDoZoo>
                <ZvířeTyp názevTypu="GorilaNížnná" />
            </Zvíře>           
            <Veterinář názevTypu="Veterinář_1"/>
            <Pečovatel názevTypu="Pečovatel_1"/>
        </Výběh>
        
        <PrůvodcePavilonem názevTypu="Průvodce_pavilonem_1"/>
    </Pavilon>



    <TypyZvířat>
        <ZvířeTyp název="Zebra">
            <název>Zebra</název>
            <popis xml:lang="cs">Bílý kůň s černýma pruhama</popis>
            <popisChovu xml:lang="cs">Zebry mají rády slunné teplé travnaté pláně, živí se trávou, senem. Zimu tráví ve stájích</popisChovu>
            <TypStravy názevTypu="Seno"/>
        </ZvířeTyp>
        
        <ZvířeTyp název="VelbloudDvouhrbý">
            <název>Velbloud dvouhrbý</název>
            <popis xml:lang="cs">Hnědý kůň s dvouma hrbama</popis>
            <popisChovu xml:lang="cs">Velbloud je velmi nenáročné zvíře, živí se trávou, senem. Zimu tráví ve stájích. Když jednou zapomenete dodat vodu, nic se nestane.</popisChovu>
            <TypStravy názevTypu="Seno"/>
        </ZvířeTyp>

        <ZvířeTyp název="PaovceHřivnatá">
            <název>Paovce hřivnatá</název>
            <popis xml:lang="cs">Jedná se o druh z podčeledi kozy a ovce původem ze skal hor v Severní Africe.</popis>
            <popisChovu xml:lang="cs">Živí se trávou, senem. Zimu tráví ve stájích.</popisChovu>
            <TypStravy názevTypu="Seno"/>
        </ZvířeTyp>

        <ZvířeTyp název="KobraKrálovská">
            <název>Kobra královská</název>
            <popis xml:lang="cs">je druhem jedovatého hada z čeledi korálovcovitých, který žije v oblasti jižní a jihovýchodní Asie.</popis>
            <popisChovu xml:lang="cs">Živí se myšmi, nutné je být opatrný, jedná se o jednovatého hada.</popisChovu>
            <TypStravy názevTypu="Myš"/>
        </ZvířeTyp>

        <ZvířeTyp název="GorilaNížnná">
            <název>Gorila Nížnná</název>
            <popis xml:lang="cs">Domovem goril jsou tropické lesy v rovníkové Africe, kde se vyskytují ve dvou oblastech oddělených deštným lesem konžské pánve.</popis>
            <popisChovu xml:lang="cs">Živí se částí rostlin, ovoce, mravenci.</popisChovu>
            <TypStravy názevTypu="Meloun"/>
        </ZvířeTyp>
    </TypyZvířat>


    <TypyStrav>
        <TypStravy název="Seno">
            <cena currency="CZK">65</cena>
            <kalorie>3160</kalorie>
        </TypStravy>
        
        <TypStravy název="Myš">
            <cena currency="CZK">80</cena>
            <kalorie>50</kalorie>
        </TypStravy>

        <TypStravy název="Meloun">
            <cena currency="CZK">130</cena>
            <kalorie>28</kalorie>
        </TypStravy>
    </TypyStrav>
    

    <Zaměstnanci>
        <Uklízeč název="Uklízeč_1">
            <givenName>Petr</givenName>   
            <familyName>Novotný</familyName>
            <plat currency="CZK">25000</plat>
            <telefonníČíslo>tel:+420 111 222 333</telefonníČíslo>
        </Uklízeč>

        <Pečovatel název="Pečovatel_1">
            <givenName>Marie</givenName>   
            <familyName>Novotná</familyName>
            <plat currency="CZK">38000</plat>
            <telefonníČíslo>tel:+420 111 222 334</telefonníČíslo>
        </Pečovatel>

        <Veterinář název="Veterinář_1">
            <givenName>Marek</givenName>   
            <familyName>Novotný</familyName>
            <plat currency="CZK">48000</plat>
            <telefonníČíslo>tel:+420 111 222 335</telefonníČíslo>
        </Veterinář>

        <PrůvodcePavilonem název="Průvodce_pavilonem_1">
            <givenName>Anna</givenName>   
            <familyName>Novotná</familyName>
            <plat currency="CZK">35000</plat>
            <telefonníČíslo>tel:+420 111 222 336</telefonníČíslo>
        </PrůvodcePavilonem>
    </Zaměstnanci>

    <Výběhy>
        <!--  zde mohou být výběhy, které nejsou v žádném Pavilonu -->
    </Výběhy>
</Zoo>
